# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170515_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'date_posted', 'ordering': ['-date_posted']},
        ),
    ]
