# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170515_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.FilePathField(default='New post cover'),
        ),
        migrations.AddField(
            model_name='post',
            name='photos',
            field=models.ImageField(default='New post photos', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='New post summary'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='New Post Title', max_length=20, unique=True),
        ),
    ]
