# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170516_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(default='New post summary', max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='New Post Title', max_length=100, unique=True),
        ),
    ]
