# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170516_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.FilePathField(blank=True, default='New post cover'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photos',
            field=models.ImageField(blank=True, default='New post photos', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(default='New post summary', max_length=150),
        ),
    ]
