# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170516_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.FilePathField(blank=True, default='New post cover', path='/home/shaibu/workspace/idea/dango/whatithink'),
        ),
    ]
