# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170516_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='post',
            name='summary',
        ),
    ]
