# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170517_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_image',
            field=models.URLField(default='/media/covering.png'),
        ),
        migrations.AddField(
            model_name='post',
            name='preview_summary',
            field=models.TextField(default='New Post Preview Summary', max_length=250),
        ),
    ]
