# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170525_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.CharField(default='/media/uploads/covering.png', max_length=100),
        ),
    ]
