# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170525_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.CharField(default='/media/defaults/preview.png', max_length=100),
        ),
    ]
