# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170525_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='preview_summary',
        ),
    ]
