# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170525_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='cat', max_length=20)),
                ('post', models.ManyToManyField(to='blog.Post')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='by',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
